#!/bin/bash

#
# SPDX-License-Identifier: MIT
#
# Copyright (C) 2015-2020 Micron Technology, Inc.  All rights reserved.
#

#doc: run all of the mpft correctness tests

mp=$(new_mpool) || err

mpiotest -T 30 $mp

cmd $sudo ${MPOOL_BIN}/mpool destroy "$mp"
