#!/bin/bash

#
# SPDX-License-Identifier: MIT
#
# Copyright (C) 2015-2020 Micron Technology, Inc.  All rights reserved.
#

#doc: run all of the mpft correctness tests

mp1=$(new_mpool) || err
mp2=$(new_mpool) || err
mp3=$(new_mpool) || err

set -x

mptest -h > /dev/null || err
mptest list -h > /dev/null || err

X=$($sudo mptest list -H |wc -l)
[ $X -eq 3 ] || err

X=$($sudo mptest list -H $mp1 |grep "${mp1}" |wc -l)
[ $X -eq 1 ] || err

X=$($sudo mptest list -H $mp2 |grep "${mp1}" |wc -l)
[ $X -eq 0 ] || err

X=$($sudo mptest list -H $mp1 $mp2 |wc -l)
[ $X -eq 2 ] || err

X=$($sudo mptest list -H $mp1 $mp2 floobie |wc -l)
[ $X -eq 2 ] || err

mptest testerr $mp1 0 |grep Success || err
mptest testerr $mp2 1 |egrep 'mpctl[.c]{0,2}:[0-9]+:' || err
mptest testerr $mp3 1 |grep 'Operation not permitted' || err

cmd $sudo ${MPOOL_BIN}/mpool destroy "$mp1"
cmd $sudo ${MPOOL_BIN}/mpool destroy "$mp2"
cmd $sudo ${MPOOL_BIN}/mpool destroy "$mp3"
