#!/bin/sh
#
# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (C) 2020 Micron Technology, Inc.  All rights reserved.
#
# https://www.debian.org/doc/debian-policy/ch-matainerscripts.html

PROG=${0##*/}
PKG=$(basename ${0%.*})

echo "${PROG} [$*]"

case $1 in
    remove|purge)
        # remove mpool related tmpfiles
        rm -fr /run/mpool

        # reload udev rules
        udevadm control --reload-rules
        ;;

    abort-upgrade)
        mpool scan --activate >/dev/null 2>&1 || echo "Failed to activate mpool(s)"
        ;;

    *)
esac

exit 0


