#!/bin/sh
#
# SPDX-License-Identifier: MIT
#
# Copyright (C) 2020 Micron Technology, Inc.  All rights reserved.
#
# https://www.debian.org/doc/debian-policy/ch-matainerscripts.html

PROG=${0##*/}
PKG=$(basename ${0%.*})

case $1 in
    install|upgrade)
        if [ -d /dev/mpool ]; then
            mpool scan --deactivate >/dev/null 2>&1 ||:
        fi
        ;;

    *)
esac

exit 0
