#!/bin/sh
#
# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (C) 2020 Micron Technology, Inc.  All rights reserved.
#
# https://www.debian.org/doc/debian-policy/ch-matainerscripts.html

PROG=${0##*/}
PKG=${0%.*}

echo "${PROG} [$*]"

case $1 in
    install)
        ;;

    upgrade|abort-upgrade)
        echo "${PROG}: dont know how to handle $1 for ${PKG} ..." >&2
        ;;

    *)
        echo "invalid command '$1'" >&2
        exit 1
        ;;
esac

exit 0
