#!/bin/sh
#
# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (C) 2020 Micron Technology, Inc.  All rights reserved.
#
# https://www.debian.org/doc/debian-policy/ch-matainerscripts.html

PROG=${0##*/}
PKG=$(basename ${0%.*})

echo "${PROG} [$*]"

case $1 in
    remove)
        if [ -d /dev/mpool ]; then
            mpool scan --deactivate >/dev/null 2>&1
            [ ! -d /dev/mpool ] || echo "Failed to deactivate mpool(s)"

            # Disable mpool systemd service
            systemctl disable mpool.service --now
        fi
        ;;

    *)
esac

exit 0
